"""empty message

Revision ID: 2b985afc12ed
Revises: b38aab979cc5
Create Date: 2023-05-15 10:25:14.306763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b985afc12ed'
down_revision = 'b38aab979cc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('barcode',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('updated',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('descs',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('descs',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('updated',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('barcode',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('image',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
